## STATIC CONFIGURATION

http:
  routers:
    nas:
      service: service_nas
      rule: Host(`nas.example.com`)
      tls:
        certresolver: le
      entryPoints:
        - websecure
    nas_:
      service: service_nas
      rule: "Host(`nas.example.com`)"
      entryPoints:
        - web


    dvr:
      service: service_dvr
      rule: Host(`dvr.example.com`)
      tls:
        certresolver: le
      entryPoints:
        - websecure
    dvr_:
      service: service_dvr
      rule: "Host(`dvr.example.com`)"
      entryPoints:
        - web

  services:
    service_nas:
      loadBalancer:
        servers:
          - url: "http://192.168.1.14:80"
 
    service_dvr:
      loadBalancer:
        servers:
          - url: "http://192.168.1.15:80"
